baseURL = "https://securek8s.dev/"
languageCode = "en-us"
title = "Kubernetes Built-in Controls Workshop"
theme = "ananke"
copyright = "Connor Gilbert and StackRox, Inc."

menus = ["main"]

Paginate = 15
SectionPagesMenu = ["section"]

[params]
  mainSections = ["post"] # Disable recent-content widget by using a non-existent content type
  recent_posts_number = 0
