apiVersion: v1
kind: Namespace
metadata:
  name: sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: sa
  labels:
    app: shell
spec:
  replicas: 1
  selector:
    matchLabels:
       app: shell
  template:
    metadata:
     labels:
       app: shell
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: nginx:latest
        name: nginx
