kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: sa
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-namespace
  namespace: sa
subjects:
- kind: ServiceAccount
  name: default
  namespace: sa
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
