apiVersion: v1
kind: Namespace
metadata:
  name: mounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mounts
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
       app: server
  template:
    metadata:
     labels:
       app: server
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
          - {name: dockersocket, mountPath: /var/run/docker.sock, readOnly: true}
          - {name: procdir, mountPath: /host/proc, readOnly: true}
          - {name: cgroups, mountPath: /host/sys/fs/cgroup, readOnly: true}
          - {name: s6-run, mountPath: /var/run/s6}
          # This one is not from Datadog:
          - {name: etchostname, mountPath: /host/etc/hostname, readOnly: true}
      volumes:
        - {name: dockersocket, hostPath: {path: /var/run/docker.sock}}
        - {name: procdir, hostPath: {path: /proc}}
        - {name: cgroups, hostPath: {path: /sys/fs/cgroup}}
        - {name: s6-run, emptyDir: {}}
        - {name: etchostname, hostPath: {path: /etc/hostname}}
