kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view
  namespace: sa
rules:
- apiGroups:
  - ''
  resources:
  - 'pods'
  verbs:
  - 'list'
  - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-namespace
  namespace: sa
subjects:
- kind: ServiceAccount
  name: default
  namespace: sa
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
